CREATE OR REPLACE VIEW `proj_inf_lv` AS 
select 
   `i`.`id` AS `id`,
   `i`.`ver` AS `ver`,
   `i`.`regras` AS `regras`,
   `i`.`titulo` AS `titulo`,
   `i`.`tipo_exten` AS `tipo_exten`,
   `i`.`nome_prof` AS `nome_prof`,
   `i`.`id_prof` AS `id_prof`,
   `i`.`campus` AS `campus`,
   `i`.`centros` AS `centros`,
   `i`.`colegiado` AS `colegiado`,
   `i`.`tide` AS `tide`,
   `i`.`vigen_ini` AS `vigen_ini`,
   `i`.`vigen_fim` AS `vigen_fim`,
   `i`.`ch_semanal` AS `ch_semanal`,
   `i`.`ch_total` AS `ch_total`,
   `i`.`situacao` AS `situacao`,
   `i`.`area_cnpq` AS `area_cnpq`,
   `i`.`area_tema1` AS `area_tema1`,
   `i`.`area_tema2` AS `area_tema2`,
   `i`.`area_extensao` AS `area_extensao`,
   `i`.`linh_ext` AS `linh_ext`,
   `i`.`resumo` AS `resumo`,
   `i`.`descricao` AS `descricao`,
   `i`.`objetivos` AS `objetivos`,
   `i`.`metodologia` AS `metodologia`,
   `i`.`prodserv_espe` AS `prodserv_espe`,
   `i`.`contribuicao` AS `contribuicao`,
   `i`.`contrap_nofinac` AS `contrap_nofinac`,
   `i`.`n_cert_prev` AS `n_cert_prev`,
   `i`.`data` AS `data`,
   `i`.`outs_info` AS `outs_info`,
   `i`.`para_avaliar` AS `para_avaliar`,
   `i`.`edt` AS `edt`,
   `i`.`created_at` AS `created_at`, 
    ifnull(`a`.`fase_seq`,(select `a`.`fase_seq` from `unespar_sistema`.`avaliacoes` `a` where ((`a`.`id_proj` = `l`.`id`) and (`a`.`ver` = (`i`.`ver` - 1))) order by `a`.`fase_seq` desc limit 1)) AS `fase_seq`,ifnull(`a`.`form`,(select `a`.`form` from `unespar_sistema`.`avaliacoes` `a` where ((`a`.`id_proj` = `l`.`id`) and (`a`.`ver` = (`i`.`ver` - 1))) order by `a`.`fase_seq` desc limit 1)) AS `form`,
   `i`.`last_result` AS `last_result`,
    (select count(1) from `unespar_sistema`.`regras_defin` `rd` where (`rd`.`id_reg` = `i`.`regras`)) AS `etapas` 
from 
  ((`unespar_sistema`.`proj_last` `l` 
  join `unespar_sistema`.`proj_inf` `i` on(((`l`.`id` = `i`.`id`) and (`l`.`ver` = `i`.`ver`)))) left join `unespar_sistema`.`avalia_last` `a` on(((`l`.`id` = `a`.`id_proj`) and (`l`.`ver` = `a`.`ver`))))