SELECT 
    i.id,
    0 ver,
    '287c102f-e5fa-11ee-b2c8-0266ad9885af' regras,
    i.titulo,
    'a' tipo_ext,
    i.tipo_exten tipo_exten,
    i.nome_prof,
    i.id_prof,
    ccc.campus,
    ccc.centros,
    ccc.colegiado,
    i.tide,
    
    i.vinculo_disciplina,
    i.vinc_exten_cult,
    i.cnpq_garea,
    i.cnpq_area,
    i.cnpq_sarea,
    i.area_extensao,
    i.linh_ext,
    i.vigen_ini,
    i.vigen_fim,
    i.ch_semanal,
    i.ch_total,
    i.resumo,
    i.justificativa,
    i.objetivos,
    i.metodologia,
    i.contribuicao,
    i.cronograma,
    i.referencia,
    i.possui_financi,
    i.proposta_associada,
    i.publico_alvo,
    i.abrangencia,
    i.financiamento_proposta,
    i.valor_financiamento,
    i.palavras_chaves,
    i.equipe,
    i.parcerias,
    i.regras
FROM 
   proj_imp i
   inner join professores p on i.id_prof = p.id
   inner join ca_ce_co ccc on p.id_colegiado = ccc.co_id
