<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return [
    'App\\' => [$baseDir.'/app'],
    'Svg\\' => [$vendorDir.'/phenx/php-svg-lib/src/Svg'],
    'Sabberworm\\CSS\\' => [$vendorDir.'/sabberworm/php-css-parser/src'],
    'Masterminds\\' => [$vendorDir.'/masterminds/html5/src'],
    'FontLib\\' => [$vendorDir.'/phenx/php-font-lib/src/FontLib'],
    'Dompdf\\' => [$vendorDir.'/dompdf/dompdf/src'],
];
