<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4a74be681584525568f6354a57eefd4b
{
    public static $prefixLengthsPsr4 = [
        'A' => [
            'App\\' => 4,
        ],
        'S' => [
            'Svg\\' => 4,
            'Sabberworm\\CSS\\' => 15,
        ],
        'M' => [
            'Masterminds\\' => 12,
        ],
        'F' => [
            'FontLib\\' => 8,
        ],
        'D' => [
            'Dompdf\\' => 7,
        ],
    ];

    public static $prefixDirsPsr4 = [
        'App\\' => [
            0 => __DIR__.'/../../app',
        ],
        'Svg\\' => [
            0 => __DIR__.'/../phenx/php-svg-lib/src/Svg',
        ],
        'Sabberworm\\CSS\\' => [
            0 => __DIR__.'/../sabberworm/php-css-parser/src',
        ],
        'Masterminds\\' => [
            0 => __DIR__.'/../masterminds/html5/src',
        ],
        'FontLib\\' => [
            0 => __DIR__.'/../phenx/php-font-lib/src/FontLib',
        ],
    ];

    public static $classMap = [
        'Composer\\InstalledVersions' => __DIR__.'/../composer/InstalledVersions.php',
        'Dompdf\\Cpdf' => __DIR__.'/../dompdf/dompdf/lib/Cpdf.php',
    ];

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4a74be681584525568f6354a57eefd4b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4a74be681584525568f6354a57eefd4b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4a74be681584525568f6354a57eefd4b::$classMap;
        }, null, ClassLoader::class);
    }
}
